name: Build Lua Project

on:
  push:
    branches:
      - main
  pull_request:
     branches:
       - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Prepare build folders
        run: |
          mkdir -p build dist
          
      - name: Copy .lua files to build folder
        run: |
          cp src/*.lua build/
          cp deps/*.lua build/

      - name: Rename easy.lua to framework.lua
        run: |
          if [ -f build/easy.lua ]; then
            mv build/easy.lua build/framework.lua
          fi

      - name: Merge .lua files into dist/easy.lua
        run: |
          echo "" > dist/easy.lua
          for file in build/*.lua; do
            echo "-- begin file: $file" >> dist/easy.lua
            cat "$file" >> dist/easy.lua
            echo "" >> dist/easy.lua
          done

      - name: Display merged easy.lua
        run: cat dist/easy.lua
